### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Hanserwei** [LyshmilyY/Math#2]
安装完字体，但是编译的时候貌似还是少字体
![af738499-0f16-4085-b8fe-7820f78655fe](https://github.com/user-attachments/assets/516c891d-813d-4569-a288-9c55d39f9e58)

**Comment by LyshmilyY** [comment]
windows还是linux系统，是否是安装字体为所有用户安装字体？

**Comment by LyshmilyY** [comment]
Windows还是 Linux系统，检查安装字体后是否选择为所有用户安装，或者检查一下自己texlive版本

终端中输入 tex --version
显示是否为最新，建议安装最新的texlive


Lyshmily.Y & 木易

________________________________
发件人: HanserWei ***@***.***>
发送时间: 2024年11月7日 19:29
收件人: LyshmilyY/Math ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LyshmilyY/Math] 编译失败 (Issue #2)


安装完字体，但是编译的时候貌似还是少字体
af738499-0f16-4085-b8fe-7820f78655fe.png (view on web)<https://github.com/user-attachments/assets/516c891d-813d-4569-a288-9c55d39f9e58>

―
